//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/c5c3/cobaltcore/internal/common/types"
	barbicanapiv1alpha1 "github.com/c5c3/cobaltcore/operators/barbican/api/v1alpha1"
	apiv1alpha1 "github.com/c5c3/cobaltcore/operators/glance/api/v1alpha1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessRule) DeepCopyInto(out *AccessRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessRule.
func (in *AccessRule) DeepCopy() *AccessRule {
	if in == nil {
		return nil
	}
	out := new(AccessRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminApplicationCredentialStatus) DeepCopyInto(out *AdminApplicationCredentialStatus) {
	*out = *in
	if in.LastRotation != nil {
		in, out := &in.LastRotation, &out.LastRotation
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminApplicationCredentialStatus.
func (in *AdminApplicationCredentialStatus) DeepCopy() *AdminApplicationCredentialStatus {
	if in == nil {
		return nil
	}
	out := new(AdminApplicationCredentialStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminCredentialSpec) DeepCopyInto(out *AdminCredentialSpec) {
	*out = *in
	out.CloudCredentialsRef = in.CloudCredentialsRef
	out.PasswordSecretRef = in.PasswordSecretRef
	in.ApplicationCredential.DeepCopyInto(&out.ApplicationCredential)
	if in.BootstrapResources != nil {
		in, out := &in.BootstrapResources, &out.BootstrapResources
		*out = make([]BootstrapResourceSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminCredentialSpec.
func (in *AdminCredentialSpec) DeepCopy() *AdminCredentialSpec {
	if in == nil {
		return nil
	}
	out := new(AdminCredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationCredentialSpec) DeepCopyInto(out *ApplicationCredentialSpec) {
	*out = *in
	if in.Restricted != nil {
		in, out := &in.Restricted, &out.Restricted
		*out = new(bool)
		**out = **in
	}
	if in.AccessRules != nil {
		in, out := &in.AccessRules, &out.AccessRules
		*out = make([]AccessRule, len(*in))
		copy(*out, *in)
	}
	out.Rotation = in.Rotation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationCredentialSpec.
func (in *ApplicationCredentialSpec) DeepCopy() *ApplicationCredentialSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationCredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarbicanDedicatedBackingServicesSpec) DeepCopyInto(out *BarbicanDedicatedBackingServicesSpec) {
	*out = *in
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(types.DatabaseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(types.CacheSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarbicanDedicatedBackingServicesSpec.
func (in *BarbicanDedicatedBackingServicesSpec) DeepCopy() *BarbicanDedicatedBackingServicesSpec {
	if in == nil {
		return nil
	}
	out := new(BarbicanDedicatedBackingServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarbicanDedicatedSecretStoreSpec) DeepCopyInto(out *BarbicanDedicatedSecretStoreSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarbicanDedicatedSecretStoreSpec.
func (in *BarbicanDedicatedSecretStoreSpec) DeepCopy() *BarbicanDedicatedSecretStoreSpec {
	if in == nil {
		return nil
	}
	out := new(BarbicanDedicatedSecretStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarbicanExternalSecretStoreSpec) DeepCopyInto(out *BarbicanExternalSecretStoreSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	if in.CABundleSecretRef != nil {
		in, out := &in.CABundleSecretRef, &out.CABundleSecretRef
		*out = new(barbicanapiv1alpha1.SecretNameRefSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarbicanExternalSecretStoreSpec.
func (in *BarbicanExternalSecretStoreSpec) DeepCopy() *BarbicanExternalSecretStoreSpec {
	if in == nil {
		return nil
	}
	out := new(BarbicanExternalSecretStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapResourceSpec) DeepCopyInto(out *BootstrapResourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapResourceSpec.
func (in *BootstrapResourceSpec) DeepCopy() *BootstrapResourceSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogImportStatus) DeepCopyInto(out *CatalogImportStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogImportStatus.
func (in *CatalogImportStatus) DeepCopy() *CatalogImportStatus {
	if in == nil {
		return nil
	}
	out := new(CatalogImportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogStatus) DeepCopyInto(out *CatalogStatus) {
	*out = *in
	if in.Imports != nil {
		in, out := &in.Imports, &out.Imports
		*out = make([]CatalogImportStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogStatus.
func (in *CatalogStatus) DeepCopy() *CatalogStatus {
	if in == nil {
		return nil
	}
	out := new(CatalogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudCredentialsRef) DeepCopyInto(out *CloudCredentialsRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudCredentialsRef.
func (in *CloudCredentialsRef) DeepCopy() *CloudCredentialsRef {
	if in == nil {
		return nil
	}
	out := new(CloudCredentialsRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlane) DeepCopyInto(out *ControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlane.
func (in *ControlPlane) DeepCopy() *ControlPlane {
	if in == nil {
		return nil
	}
	out := new(ControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneList) DeepCopyInto(out *ControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneList.
func (in *ControlPlaneList) DeepCopy() *ControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneRefSpec) DeepCopyInto(out *ControlPlaneRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneRefSpec.
func (in *ControlPlaneRefSpec) DeepCopy() *ControlPlaneRefSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneSpec) DeepCopyInto(out *ControlPlaneSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(InfrastructureSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretStoreRef != nil {
		in, out := &in.SecretStoreRef, &out.SecretStoreRef
		*out = new(types.SecretStoreRefSpec)
		**out = **in
	}
	in.Services.DeepCopyInto(&out.Services)
	if in.GlobalPolicyOverrides != nil {
		in, out := &in.GlobalPolicyOverrides, &out.GlobalPolicyOverrides
		*out = new(types.PolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GlobalExtraConfig != nil {
		in, out := &in.GlobalExtraConfig, &out.GlobalExtraConfig
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	in.KORC.DeepCopyInto(&out.KORC)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneSpec.
func (in *ControlPlaneSpec) DeepCopy() *ControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneStatus) DeepCopyInto(out *ControlPlaneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]ServiceStatus, len(*in))
		copy(*out, *in)
	}
	if in.AdminApplicationCredential != nil {
		in, out := &in.AdminApplicationCredential, &out.AdminApplicationCredential
		*out = new(AdminApplicationCredentialStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = new(CatalogStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneStatus.
func (in *ControlPlaneStatus) DeepCopy() *ControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRotation) DeepCopyInto(out *CredentialRotation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRotation.
func (in *CredentialRotation) DeepCopy() *CredentialRotation {
	if in == nil {
		return nil
	}
	out := new(CredentialRotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialRotation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRotationList) DeepCopyInto(out *CredentialRotationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CredentialRotation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRotationList.
func (in *CredentialRotationList) DeepCopy() *CredentialRotationList {
	if in == nil {
		return nil
	}
	out := new(CredentialRotationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialRotationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRotationSpec) DeepCopyInto(out *CredentialRotationSpec) {
	*out = *in
	if in.IntervalDays != nil {
		in, out := &in.IntervalDays, &out.IntervalDays
		*out = new(int32)
		**out = **in
	}
	if in.PreRotationDays != nil {
		in, out := &in.PreRotationDays, &out.PreRotationDays
		*out = new(int32)
		**out = **in
	}
	if in.GracePeriodDays != nil {
		in, out := &in.GracePeriodDays, &out.GracePeriodDays
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRotationSpec.
func (in *CredentialRotationSpec) DeepCopy() *CredentialRotationSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialRotationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRotationStatus) DeepCopyInto(out *CredentialRotationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRotationStatus.
func (in *CredentialRotationStatus) DeepCopy() *CredentialRotationStatus {
	if in == nil {
		return nil
	}
	out := new(CredentialRotationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalCatalogSpec) DeepCopyInto(out *ExternalCatalogSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalCatalogSpec.
func (in *ExternalCatalogSpec) DeepCopy() *ExternalCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalKeystoneSpec) DeepCopyInto(out *ExternalKeystoneSpec) {
	*out = *in
	if in.CABundleSecretRef != nil {
		in, out := &in.CABundleSecretRef, &out.CABundleSecretRef
		*out = new(types.SecretRefSpec)
		**out = **in
	}
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = new(ExternalCatalogSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalKeystoneSpec.
func (in *ExternalKeystoneSpec) DeepCopy() *ExternalKeystoneSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalKeystoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlanceBackendEntry) DeepCopyInto(out *GlanceBackendEntry) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(GlanceBackendS3Spec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlanceBackendEntry.
func (in *GlanceBackendEntry) DeepCopy() *GlanceBackendEntry {
	if in == nil {
		return nil
	}
	out := new(GlanceBackendEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlanceBackendS3Spec) DeepCopyInto(out *GlanceBackendS3Spec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlanceBackendS3Spec.
func (in *GlanceBackendS3Spec) DeepCopy() *GlanceBackendS3Spec {
	if in == nil {
		return nil
	}
	out := new(GlanceBackendS3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlanceDedicatedBackingServicesSpec) DeepCopyInto(out *GlanceDedicatedBackingServicesSpec) {
	*out = *in
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(types.DatabaseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(types.CacheSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlanceDedicatedBackingServicesSpec.
func (in *GlanceDedicatedBackingServicesSpec) DeepCopy() *GlanceDedicatedBackingServicesSpec {
	if in == nil {
		return nil
	}
	out := new(GlanceDedicatedBackingServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizonDedicatedBackingServicesSpec) DeepCopyInto(out *HorizonDedicatedBackingServicesSpec) {
	*out = *in
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(types.CacheSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizonDedicatedBackingServicesSpec.
func (in *HorizonDedicatedBackingServicesSpec) DeepCopy() *HorizonDedicatedBackingServicesSpec {
	if in == nil {
		return nil
	}
	out := new(HorizonDedicatedBackingServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureSpec) DeepCopyInto(out *InfrastructureSpec) {
	*out = *in
	in.Database.DeepCopyInto(&out.Database)
	in.Cache.DeepCopyInto(&out.Cache)
	if in.Messaging != nil {
		in, out := &in.Messaging, &out.Messaging
		*out = new(types.MessagingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureSpec.
func (in *InfrastructureSpec) DeepCopy() *InfrastructureSpec {
	if in == nil {
		return nil
	}
	out := new(InfrastructureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KORCSpec) DeepCopyInto(out *KORCSpec) {
	*out = *in
	in.AdminCredential.DeepCopyInto(&out.AdminCredential)
	if in.ServiceRegistrations != nil {
		in, out := &in.ServiceRegistrations, &out.ServiceRegistrations
		*out = new(ServiceRegistrationsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KORCSpec.
func (in *KORCSpec) DeepCopy() *KORCSpec {
	if in == nil {
		return nil
	}
	out := new(KORCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneDedicatedBackingServicesSpec) DeepCopyInto(out *KeystoneDedicatedBackingServicesSpec) {
	*out = *in
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(types.DatabaseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(types.CacheSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneDedicatedBackingServicesSpec.
func (in *KeystoneDedicatedBackingServicesSpec) DeepCopy() *KeystoneDedicatedBackingServicesSpec {
	if in == nil {
		return nil
	}
	out := new(KeystoneDedicatedBackingServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneService) DeepCopyInto(out *KeystoneService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneService.
func (in *KeystoneService) DeepCopy() *KeystoneService {
	if in == nil {
		return nil
	}
	out := new(KeystoneService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeystoneService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneServiceAccountSpec) DeepCopyInto(out *KeystoneServiceAccountSpec) {
	*out = *in
	out.Project = in.Project
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Rotation != nil {
		in, out := &in.Rotation, &out.Rotation
		*out = new(ServiceAccountRotationSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneServiceAccountSpec.
func (in *KeystoneServiceAccountSpec) DeepCopy() *KeystoneServiceAccountSpec {
	if in == nil {
		return nil
	}
	out := new(KeystoneServiceAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneServiceAccountStatus) DeepCopyInto(out *KeystoneServiceAccountStatus) {
	*out = *in
	if in.LastPasswordRotation != nil {
		in, out := &in.LastPasswordRotation, &out.LastPasswordRotation
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneServiceAccountStatus.
func (in *KeystoneServiceAccountStatus) DeepCopy() *KeystoneServiceAccountStatus {
	if in == nil {
		return nil
	}
	out := new(KeystoneServiceAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneServiceCatalogSpec) DeepCopyInto(out *KeystoneServiceCatalogSpec) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]KeystoneServiceEndpointSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneServiceCatalogSpec.
func (in *KeystoneServiceCatalogSpec) DeepCopy() *KeystoneServiceCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(KeystoneServiceCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneServiceCatalogStatus) DeepCopyInto(out *KeystoneServiceCatalogStatus) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]KeystoneServiceEndpointStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneServiceCatalogStatus.
func (in *KeystoneServiceCatalogStatus) DeepCopy() *KeystoneServiceCatalogStatus {
	if in == nil {
		return nil
	}
	out := new(KeystoneServiceCatalogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneServiceEndpointSpec) DeepCopyInto(out *KeystoneServiceEndpointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneServiceEndpointSpec.
func (in *KeystoneServiceEndpointSpec) DeepCopy() *KeystoneServiceEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(KeystoneServiceEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneServiceEndpointStatus) DeepCopyInto(out *KeystoneServiceEndpointStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneServiceEndpointStatus.
func (in *KeystoneServiceEndpointStatus) DeepCopy() *KeystoneServiceEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(KeystoneServiceEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneServiceList) DeepCopyInto(out *KeystoneServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeystoneService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneServiceList.
func (in *KeystoneServiceList) DeepCopy() *KeystoneServiceList {
	if in == nil {
		return nil
	}
	out := new(KeystoneServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeystoneServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneServiceSpec) DeepCopyInto(out *KeystoneServiceSpec) {
	*out = *in
	out.ControlPlaneRef = in.ControlPlaneRef
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = new(KeystoneServiceCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Account != nil {
		in, out := &in.Account, &out.Account
		*out = new(KeystoneServiceAccountSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneServiceSpec.
func (in *KeystoneServiceSpec) DeepCopy() *KeystoneServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KeystoneServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneServiceStatus) DeepCopyInto(out *KeystoneServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = new(KeystoneServiceCatalogStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Account != nil {
		in, out := &in.Account, &out.Account
		*out = new(KeystoneServiceAccountStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneServiceStatus.
func (in *KeystoneServiceStatus) DeepCopy() *KeystoneServiceStatus {
	if in == nil {
		return nil
	}
	out := new(KeystoneServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeutronDedicatedBackingServicesSpec) DeepCopyInto(out *NeutronDedicatedBackingServicesSpec) {
	*out = *in
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(types.DatabaseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(types.CacheSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeutronDedicatedBackingServicesSpec.
func (in *NeutronDedicatedBackingServicesSpec) DeepCopy() *NeutronDedicatedBackingServicesSpec {
	if in == nil {
		return nil
	}
	out := new(NeutronDedicatedBackingServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeutronOVNCentralRef) DeepCopyInto(out *NeutronOVNCentralRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeutronOVNCentralRef.
func (in *NeutronOVNCentralRef) DeepCopy() *NeutronOVNCentralRef {
	if in == nil {
		return nil
	}
	out := new(NeutronOVNCentralRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeutronOVNSpec) DeepCopyInto(out *NeutronOVNSpec) {
	*out = *in
	out.CentralRef = in.CentralRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeutronOVNSpec.
func (in *NeutronOVNSpec) DeepCopy() *NeutronOVNSpec {
	if in == nil {
		return nil
	}
	out := new(NeutronOVNSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementDedicatedBackingServicesSpec) DeepCopyInto(out *PlacementDedicatedBackingServicesSpec) {
	*out = *in
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(types.DatabaseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(types.CacheSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementDedicatedBackingServicesSpec.
func (in *PlacementDedicatedBackingServicesSpec) DeepCopy() *PlacementDedicatedBackingServicesSpec {
	if in == nil {
		return nil
	}
	out := new(PlacementDedicatedBackingServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationSpec) DeepCopyInto(out *RotationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationSpec.
func (in *RotationSpec) DeepCopy() *RotationSpec {
	if in == nil {
		return nil
	}
	out := new(RotationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretAggregate) DeepCopyInto(out *SecretAggregate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretAggregate.
func (in *SecretAggregate) DeepCopy() *SecretAggregate {
	if in == nil {
		return nil
	}
	out := new(SecretAggregate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretAggregate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretAggregateList) DeepCopyInto(out *SecretAggregateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretAggregate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretAggregateList.
func (in *SecretAggregateList) DeepCopy() *SecretAggregateList {
	if in == nil {
		return nil
	}
	out := new(SecretAggregateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretAggregateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretAggregateSpec) DeepCopyInto(out *SecretAggregateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretAggregateSpec.
func (in *SecretAggregateSpec) DeepCopy() *SecretAggregateSpec {
	if in == nil {
		return nil
	}
	out := new(SecretAggregateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretAggregateStatus) DeepCopyInto(out *SecretAggregateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretAggregateStatus.
func (in *SecretAggregateStatus) DeepCopy() *SecretAggregateStatus {
	if in == nil {
		return nil
	}
	out := new(SecretAggregateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretNameRef) DeepCopyInto(out *SecretNameRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretNameRef.
func (in *SecretNameRef) DeepCopy() *SecretNameRef {
	if in == nil {
		return nil
	}
	out := new(SecretNameRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountProjectSpec) DeepCopyInto(out *ServiceAccountProjectSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountProjectSpec.
func (in *ServiceAccountProjectSpec) DeepCopy() *ServiceAccountProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountRotationSpec) DeepCopyInto(out *ServiceAccountRotationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountRotationSpec.
func (in *ServiceAccountRotationSpec) DeepCopy() *ServiceAccountRotationSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountRotationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBarbicanSecretStoreSpec) DeepCopyInto(out *ServiceBarbicanSecretStoreSpec) {
	*out = *in
	if in.Dedicated != nil {
		in, out := &in.Dedicated, &out.Dedicated
		*out = new(BarbicanDedicatedSecretStoreSpec)
		**out = **in
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(BarbicanExternalSecretStoreSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBarbicanSecretStoreSpec.
func (in *ServiceBarbicanSecretStoreSpec) DeepCopy() *ServiceBarbicanSecretStoreSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceBarbicanSecretStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBarbicanSpec) DeepCopyInto(out *ServiceBarbicanSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(types.ImageSpec)
		**out = **in
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(types.GatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	in.SecretStore.DeepCopyInto(&out.SecretStore)
	if in.DedicatedBackingServices != nil {
		in, out := &in.DedicatedBackingServices, &out.DedicatedBackingServices
		*out = new(BarbicanDedicatedBackingServicesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(ServiceNamespaceSpec)
		**out = **in
	}
	if in.TargetClusterRef != nil {
		in, out := &in.TargetClusterRef, &out.TargetClusterRef
		*out = new(types.TargetClusterRefSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBarbicanSpec.
func (in *ServiceBarbicanSpec) DeepCopy() *ServiceBarbicanSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceBarbicanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceGlanceSpec) DeepCopyInto(out *ServiceGlanceSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(types.ImageSpec)
		**out = **in
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(types.GatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]GlanceBackendEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImportFiltering != nil {
		in, out := &in.ImportFiltering, &out.ImportFiltering
		*out = new(apiv1alpha1.ImportFilteringSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Staging != nil {
		in, out := &in.Staging, &out.Staging
		*out = new(apiv1alpha1.StagingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageCache != nil {
		in, out := &in.ImageCache, &out.ImageCache
		*out = new(apiv1alpha1.ImageCacheSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ImportPlugins != nil {
		in, out := &in.ImportPlugins, &out.ImportPlugins
		*out = new(apiv1alpha1.ImportPluginsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.DedicatedBackingServices != nil {
		in, out := &in.DedicatedBackingServices, &out.DedicatedBackingServices
		*out = new(GlanceDedicatedBackingServicesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(ServiceNamespaceSpec)
		**out = **in
	}
	if in.TargetClusterRef != nil {
		in, out := &in.TargetClusterRef, &out.TargetClusterRef
		*out = new(types.TargetClusterRefSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceGlanceSpec.
func (in *ServiceGlanceSpec) DeepCopy() *ServiceGlanceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceGlanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceHorizonSpec) DeepCopyInto(out *ServiceHorizonSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(types.ImageSpec)
		**out = **in
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(types.GatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(types.SecretRefSpec)
		**out = **in
	}
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.DedicatedBackingServices != nil {
		in, out := &in.DedicatedBackingServices, &out.DedicatedBackingServices
		*out = new(HorizonDedicatedBackingServicesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(ServiceNamespaceSpec)
		**out = **in
	}
	if in.TargetClusterRef != nil {
		in, out := &in.TargetClusterRef, &out.TargetClusterRef
		*out = new(types.TargetClusterRefSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceHorizonSpec.
func (in *ServiceHorizonSpec) DeepCopy() *ServiceHorizonSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceHorizonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceKeystoneSpec) DeepCopyInto(out *ServiceKeystoneSpec) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalKeystoneSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(types.ImageSpec)
		**out = **in
	}
	if in.PolicyOverrides != nil {
		in, out := &in.PolicyOverrides, &out.PolicyOverrides
		*out = new(types.PolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.RotationInterval != nil {
		in, out := &in.RotationInterval, &out.RotationInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(types.GatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.FederationProxyImage != nil {
		in, out := &in.FederationProxyImage, &out.FederationProxyImage
		*out = new(types.ImageSpec)
		**out = **in
	}
	if in.DedicatedBackingServices != nil {
		in, out := &in.DedicatedBackingServices, &out.DedicatedBackingServices
		*out = new(KeystoneDedicatedBackingServicesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(ServiceNamespaceSpec)
		**out = **in
	}
	if in.TargetClusterRef != nil {
		in, out := &in.TargetClusterRef, &out.TargetClusterRef
		*out = new(types.TargetClusterRefSpec)
		**out = **in
	}
	if in.CABundleSecretRef != nil {
		in, out := &in.CABundleSecretRef, &out.CABundleSecretRef
		*out = new(types.SecretRefSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKeystoneSpec.
func (in *ServiceKeystoneSpec) DeepCopy() *ServiceKeystoneSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceKeystoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceNamespaceSpec) DeepCopyInto(out *ServiceNamespaceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceNamespaceSpec.
func (in *ServiceNamespaceSpec) DeepCopy() *ServiceNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceNeutronSpec) DeepCopyInto(out *ServiceNeutronSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.WorkerReplicas != nil {
		in, out := &in.WorkerReplicas, &out.WorkerReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(types.ImageSpec)
		**out = **in
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(types.GatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	out.OVN = in.OVN
	if in.DedicatedBackingServices != nil {
		in, out := &in.DedicatedBackingServices, &out.DedicatedBackingServices
		*out = new(NeutronDedicatedBackingServicesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(ServiceNamespaceSpec)
		**out = **in
	}
	if in.TargetClusterRef != nil {
		in, out := &in.TargetClusterRef, &out.TargetClusterRef
		*out = new(types.TargetClusterRefSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceNeutronSpec.
func (in *ServiceNeutronSpec) DeepCopy() *ServiceNeutronSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceNeutronSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePlacementSpec) DeepCopyInto(out *ServicePlacementSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(types.ImageSpec)
		**out = **in
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(types.GatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.DedicatedBackingServices != nil {
		in, out := &in.DedicatedBackingServices, &out.DedicatedBackingServices
		*out = new(PlacementDedicatedBackingServicesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(ServiceNamespaceSpec)
		**out = **in
	}
	if in.TargetClusterRef != nil {
		in, out := &in.TargetClusterRef, &out.TargetClusterRef
		*out = new(types.TargetClusterRefSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePlacementSpec.
func (in *ServicePlacementSpec) DeepCopy() *ServicePlacementSpec {
	if in == nil {
		return nil
	}
	out := new(ServicePlacementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistrationsSpec) DeepCopyInto(out *ServiceRegistrationsSpec) {
	*out = *in
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistrationsSpec.
func (in *ServiceRegistrationsSpec) DeepCopy() *ServiceRegistrationsSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistrationsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicesSpec) DeepCopyInto(out *ServicesSpec) {
	*out = *in
	if in.Keystone != nil {
		in, out := &in.Keystone, &out.Keystone
		*out = new(ServiceKeystoneSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Horizon != nil {
		in, out := &in.Horizon, &out.Horizon
		*out = new(ServiceHorizonSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Glance != nil {
		in, out := &in.Glance, &out.Glance
		*out = new(ServiceGlanceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(ServicePlacementSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Barbican != nil {
		in, out := &in.Barbican, &out.Barbican
		*out = new(ServiceBarbicanSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Neutron != nil {
		in, out := &in.Neutron, &out.Neutron
		*out = new(ServiceNeutronSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicesSpec.
func (in *ServicesSpec) DeepCopy() *ServicesSpec {
	if in == nil {
		return nil
	}
	out := new(ServicesSpec)
	in.DeepCopyInto(out)
	return out
}
