version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic
  exclusions:
    rules:
      - path: "zz_generated.*\\.go$"
        linters:
          - govet
          - errcheck
          - staticcheck
          - unused
          - ineffassign
          - gocritic
