{{/*
SOURCE: operators/c5c3/config/rbac/role.yaml
GENERATED by hack/gen-helm-rbac-rules.py from the kubebuilder RBAC markers in
operators/c5c3; do not edit. The leases rule is appended for leader election.
Run 'make verify-helm-rbac' to check for drift, or 'make sync-helm-rbac' to update.
*/}}
{{- define "c5c3-operator.rbacRules" -}}
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - barbican.openstack.c5c3.io
  resources:
  - barbicans
  - barbicansecretstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - c5c3.io
  resources:
  - controlplanes
  - credentialrotations
  - keystoneservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - c5c3.io
  resources:
  - controlplanes/finalizers
  - keystoneservices/finalizers
  verbs:
  - update
- apiGroups:
  - c5c3.io
  resources:
  - controlplanes/status
  - credentialrotations/status
  - keystoneservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - c5c3.io
  resources:
  - secretaggregates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
- apiGroups:
  - external-secrets.io
  resources:
  - clustersecretstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  - pushsecrets
  - secretstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - generators.external-secrets.io
  resources:
  - vaultdynamicsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - glance.openstack.c5c3.io
  resources:
  - glancebackends
  - glances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - horizon.openstack.c5c3.io
  resources:
  - horizons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.mariadb.com
  resources:
  - mariadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keystone.openstack.c5c3.io
  resources:
  - keystoneidentitybackends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keystone.openstack.c5c3.io
  resources:
  - keystones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memcached.c5c3.io
  resources:
  - memcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neutron.openstack.c5c3.io
  resources:
  - neutrons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openbao.org
  resources:
  - openbaoclusters
  - openbaotenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - applicationcredentials
  - domains
  - endpoints
  - projects
  - roleassignments
  - roles
  - services
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovn.openstack.c5c3.io
  resources:
  - ovncentrals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - placement.openstack.c5c3.io
  resources:
  - placements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - system:auth-delegator
  resources:
  - clusterroles
  verbs:
  - bind
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
{{- end }}
