apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalsecrets.external-secrets.io
spec:
  group: external-secrets.io
  names:
    plural: externalsecrets
    singular: externalsecret
    kind: ExternalSecret
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                refreshInterval:
                  type: string
                secretStoreRef:
                  type: object
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
                target:
                  type: object
                  properties:
                    name:
                      type: string
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      secretKey:
                        type: string
                      remoteRef:
                        type: object
                        properties:
                          key:
                            type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                    required:
                      - type
                      - status
                syncedResourceVersion:
                  type: string
