apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pushsecrets.external-secrets.io
spec:
  group: external-secrets.io
  names:
    plural: pushsecrets
    singular: pushsecret
    kind: PushSecret
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                secretStoreRefs:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      kind:
                        type: string
                selector:
                  type: object
                  properties:
                    secret:
                      type: object
                      properties:
                        name:
                          type: string
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      match:
                        type: object
                        properties:
                          secretKey:
                            type: string
                          remoteRef:
                            type: object
                            properties:
                              remoteKey:
                                type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                    required:
                      - type
                      - status
